### ISSUE TITLE
Split out the logic for getting dependencies

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-migration-guru#9]
This helps us move towards https://github.com/orgs/Financial-Times/projects/73#card-24448931

**Objective:** Understand our users
**Key Result:** Understand where each of our 53 active/maintained components are used across the FT

**Comment by notlee** [comment]
origami-migration-guru started as a 10% time project. It was
useful during the [2019 major cascade](https://origami.ft.com/blog/2019/10/31/major-cascade/) but is not easy to use, 
for example requiring a list of all manifest files, and is not 100% 
reliable. It needs more work and has therefore been marked as dead.

https://github.com/Financial-Times/origami-migration-guru/pull/49

_Hi Rowan! Hi!_
